[package]
name = "implemented_CAL_environment"
version = "0.1.0"
edition = "2021"

[dependencies]
crypto-layer = {version="0.1.0", path="binaryknights_rust_crypto", features=["macos", "tpm"]}
apple-secure-enclave-bindings = {version = "0.1.0", path="binaryknights_rust_crypto/src/tpm/macos/main"}
